rlslam:
  
  steps_in_episode: 500
  
  initial_posx: 0.0
  initial_posy: 0.0
  
  obs_space_max:
    px: 2.
    py: 10.
    qz: inf
   
  obs_space_min:
    px: -2.
    py: 2
    qz: -inf

  maze_size: 20  

  scan_max_distance: 4.0
  scan_min_distance: 0.2
  training_image_size: 8
  crash_distance: 0.21
  map_completed_threshold: 0.85
  reward_map_completed: 0.1
  reward_crashed: -0.1

  steering: 1.0
  throttle: 0.2 
  linear_throttle: 0.25
  turn_throttle: 0.0


  timeout: 5.0
  sleep_reset_time: 1.0
